name: Deploy ke VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          cd /var/www/pinote
          git fetch origin main
          git reset --hard origin/main
          npm --prefix backend install --no-audit --no-fund
          npm --prefix frontend install --no-audit --no-fund
          npm run build
          npm --prefix backend run db:migrate
          pm2 startOrRestart ecosystem.config.json
          pm2 save
